annotate errors with code location
right now it looks like this:

    $ go run ./cmd/bass demos/fib.bass
    --------------------------------------------------
    fib applicative? combiner?
    args: [n]

    calculate the value at the given offset of the fibonacci sequence

    Error: unbound symbol: emit
    demos/fib.bass  10:1..10:5
            emit
    demos/fib.bass  9:8..10:15
            (emit (fib 20))
    exit status 1

going to iterate on this as I go. showing a highlighted code snippet
could be cool. gonna try that next, committing this first in case I back
out.

+ removed a few tests for error conditions that felt out of place and
  suddenly became a pain in the butt to maintain. equivalent tests don't
  exist for all other operators. would rather add tests for errors once
  they become more intentionally designed.

+ switch tests over to use Value.Equal now that parsed expressions end
  up wrapped in an Annotated type. (could use a refactor to introduce an
  equality assertion helper function.)

Signed-off-by: Alex Suraci <suraci.alex@gmail.com>